/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Time */
        get: operations["get_time_time_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/situational_picture/{which}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Situational Picture */
        post: operations["get_situational_picture_situational_picture__which__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ground_truth/{which}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Ground Truth */
        post: operations["get_ground_truth_ground_truth__which__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculate_monostatic_coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calculate Monostatic Coverage */
        post: operations["calculate_monostatic_coverage_calculate_monostatic_coverage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Health */
        get: operations["check_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/is_paused": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is Paused */
        get: operations["is_paused_is_paused_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttenuationModel */
        AttenuationModel: {
            /** Attenuation Table Angles */
            attenuation_table_angles: number[];
            /** Attenuation Table Values */
            attenuation_table_values: number[];
            polarization: components["schemas"]["Polarization"];
        };
        /** ExtrapolatedGroundtruth */
        ExtrapolatedGroundtruth: {
            /** Target Id */
            target_id: number;
            /** Points */
            points: components["schemas"]["TrackPoint"][];
        };
        /** ExtrapolatedSituationalPicture */
        ExtrapolatedSituationalPicture: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Friendly Radars */
            friendly_radars: components["schemas"]["Radar-Output"][];
            /** Enemy Tracks */
            enemy_tracks: components["schemas"]["ExtrapolatedTrack"][];
        };
        /** ExtrapolatedTrack */
        ExtrapolatedTrack: {
            /** Id */
            id: string;
            /** Points */
            points: components["schemas"]["TrackPoint"][];
        };
        /** GeoJSONFeature */
        GeoJSONFeature: {
            /**
             * Type
             * @default Feature
             */
            type: string;
            geometry: components["schemas"]["GeoJSONPolygon"];
            /**
             * Properties
             * @default {}
             */
            properties: {
                [key: string]: unknown;
            };
        };
        /** GeoJSONPolygon */
        GeoJSONPolygon: {
            /**
             * Type
             * @default Polygon
             */
            type: string;
            /** Coordinates */
            coordinates: number[][][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MonostaticRadarMeasurementModel */
        MonostaticRadarMeasurementModel: {
            /**
             * Min Range Uncertainty
             * @default 100
             */
            min_range_uncertainty: number;
            /** Max Range Uncertainty */
            max_range_uncertainty?: number;
            /** Min Angular Uncertainty */
            min_angular_uncertainty?: number;
            /** Max Angular Uncertainty */
            max_angular_uncertainty?: number;
        };
        /** Point */
        Point: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Alt */
            alt: number;
        };
        /**
         * Polarization
         * @enum {integer}
         */
        Polarization: 0 | 1;
        /** Radar */
        "Radar-Input": {
            transmitter: components["schemas"]["Transmitter-Input"];
            receiver: components["schemas"]["Receiver-Input"];
            error_model: components["schemas"]["MonostaticRadarMeasurementModel"];
        };
        /** Radar */
        "Radar-Output": {
            transmitter: components["schemas"]["Transmitter-Output"];
            receiver: components["schemas"]["Receiver-Output"];
            error_model: components["schemas"]["MonostaticRadarMeasurementModel"];
        };
        /** Receiver */
        "Receiver-Input": {
            /** Id */
            id: number;
            point: components["schemas"]["Point"];
            /** Antenna Height */
            antenna_height: number;
            /** Diameter */
            diameter: number;
            /** Cpi Pulses */
            cpi_pulses: number;
            /** Pfa */
            pfa: number;
            /** Min Elevation */
            min_elevation: number;
            /** Max Elevation */
            max_elevation: number;
            /** Rotation Time */
            rotation_time: number;
            /** Bandwidth */
            bandwidth: number;
            /**
             * Gain
             * @default 0
             */
            gain: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Noise Temperature
             * @default 300
             */
            noise_temperature: number;
            /**
             * Noise Figure
             * @default 1.9
             */
            noise_figure: number;
            /**
             * Antenna Efficiency Value
             * @default 0.6
             */
            antenna_efficiency_value: number;
            vertical_attenuation?: components["schemas"]["AttenuationModel"] | null;
            horizontal_attenuation?: components["schemas"]["AttenuationModel"] | null;
        };
        /** Receiver */
        "Receiver-Output": {
            /** Id */
            id: number;
            point: components["schemas"]["Point"];
            /** Antenna Height */
            antenna_height: number;
            /** Diameter */
            diameter: number;
            /** Cpi Pulses */
            cpi_pulses: number;
            /** Pfa */
            pfa: number;
            /** Min Elevation */
            min_elevation: number;
            /** Max Elevation */
            max_elevation: number;
            /** Rotation Time */
            rotation_time: number;
            /** Bandwidth */
            bandwidth: number;
            /**
             * Gain
             * @default 0
             */
            gain: number;
            /**
             * Losses
             * @default 0
             */
            losses: number;
            /**
             * Noise Temperature
             * @default 300
             */
            noise_temperature: number;
            /**
             * Noise Figure
             * @default 1.9
             */
            noise_figure: number;
            /**
             * Antenna Efficiency Value
             * @default 0.6
             */
            antenna_efficiency_value: number;
            vertical_attenuation?: components["schemas"]["AttenuationModel"] | null;
            horizontal_attenuation?: components["schemas"]["AttenuationModel"] | null;
        };
        /**
         * Team
         * @enum {string}
         */
        Team: "BLUE" | "RED";
        /** TrackPoint */
        TrackPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Alt */
            alt: number;
            /** V East */
            v_east: number;
            /** V North */
            v_north: number;
            /** V Up */
            v_up: number;
        };
        /** Transmitter */
        "Transmitter-Input": {
            /** Id */
            id: number;
            point: components["schemas"]["Point"];
            /** Power */
            power: number;
            /** Erp */
            erp: number;
            /** Antenna Height */
            antenna_height: number;
            /** Antenna Diameter */
            antenna_diameter: number;
            /** Frequency */
            frequency: number;
            /** Pulse Width */
            pulse_width: number;
            polarization: components["schemas"]["Polarization"];
            /** Bandwidth */
            bandwidth: number;
            /**
             * Max Coherent Integration Time
             * @default 0.5
             */
            max_coherent_integration_time: number;
            /**
             * Antenna Efficiency Value
             * @default 0.6
             */
            antenna_efficiency_value: number;
            vertical_attenuation?: components["schemas"]["AttenuationModel"] | null;
            horizontal_attenuation?: components["schemas"]["AttenuationModel"] | null;
        };
        /** Transmitter */
        "Transmitter-Output": {
            /** Id */
            id: number;
            point: components["schemas"]["Point"];
            /** Power */
            power: number;
            /** Erp */
            erp: number;
            /** Antenna Height */
            antenna_height: number;
            /** Antenna Diameter */
            antenna_diameter: number;
            /** Frequency */
            frequency: number;
            /** Pulse Width */
            pulse_width: number;
            polarization: components["schemas"]["Polarization"];
            /** Bandwidth */
            bandwidth: number;
            /**
             * Max Coherent Integration Time
             * @default 0.5
             */
            max_coherent_integration_time: number;
            /**
             * Antenna Efficiency Value
             * @default 0.6
             */
            antenna_efficiency_value: number;
            vertical_attenuation?: components["schemas"]["AttenuationModel"] | null;
            horizontal_attenuation?: components["schemas"]["AttenuationModel"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_time_time_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_situational_picture_situational_picture__which__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                which: components["schemas"]["Team"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtrapolatedSituationalPicture"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ground_truth_ground_truth__which__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                which: components["schemas"]["Team"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtrapolatedGroundtruth"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_monostatic_coverage_calculate_monostatic_coverage_post: {
        parameters: {
            query: {
                target_alt: number;
                rcs: number;
                probability_threshold: number;
                azimuth_resolution_degree: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Radar-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeoJSONFeature"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    pause_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    resume_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    is_paused_is_paused_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": boolean;
                };
            };
        };
    };
}
